### ISSUE TITLE
Problem installing the requeriments

### ISSUE THREAD

**Issue by amfgomez** [telefonicaid/orchestrator#162]
Hello everyone.

I am following the installation guide. When I execute the command below:
    pip install -r requirement.txt
I have got the following error:
 x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=3.0.0 -DLDAPMODULE_AUTHOR=python-ldap project -DLDAPMODULE_LICENSE=Python style -IModules -I/usr/include/python2.7 -c Modules/LDAPObject.c -o build/temp.linux-x86_64-2.7/Modules/LDAPObject.o
    In file included from Modules/LDAPObject.c:8:0:
    Modules/constants.h:7:18: fatal error: lber.h: No existe el archivo o el directorio
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-WrJf1x/python-ldap/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-QkOxPe/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-WrJf1x/python-ldap/

Do someone knows to solve the error?
Thank you very much.
Best regard.

**Comment by AlvaroVega** [comment]
Your issue is described in: https://stackoverflow.com/questions/4768446/i-cant-install-python-ldap
Depending on your O.S: you need to install some development files (headers).
