### ISSUE TITLE
Keystone Problem autorization

### ISSUE THREAD

**Issue by amfgomez** [telefonicaid/orchestrator#163]
Hello

I have deployment every docker like it is described in Manual.
I have executed the following command to get a token:
curl localhost:5001/v3/auth/tokens -s -S --header 'Content-Type: application/json' -d @- <<EOF 
{ "auth": {
     "identity": { 
         "methods": ["password"], 
              "password": { 
                  "user":{ 
                     "name": "cloud_admin", 
                     "domain": { "name": "admin_domain" }, 
                     "password": "4pass1w0rd"
                   }
                }
            }
      }
}

I check in Mysql database that this user is created:
{
    "token": {
        "methods": [
            "password"
        ],
        "expires_at": "2018-08-30T11:52:40.044334Z",
        "extras": {
            "password_creation_time": "2018-08-30T10:42:53Z",
            "last_login_attempt_time": "2018-08-30T10:48:27.000000",
            "pwd_user_in_blacklist": true,
            "password_expiration_time": "2019-08-30T10:42:53Z"
        },
        "user": {
            "domain": {
                "id": "ab458c371df547e486f25e29dea8705e",
                "name": "admin_domain"
            },
            "id": "3538ae754cb44599bc7fac1e93750cd2",
            "name": "cloud_admin"
        },
        "audit_ids": [
            "1e7R-69ESdCemFuIV2B9Fg"
        ],
        "issued_at": "2018-08-30T10:52:40.044357Z"
    }
}
Keysone does not return the token.

**Comment by AlvaroVega** [comment]
Token is in x-subject-token header of response
