### ISSUE TITLE
Error executing Script

### ISSUE THREAD

**Issue by amfgomez** [telefonicaid/orchestrator#164]
Hello 

I am running provision_smartcity.sh to create a test environment. I got the following error:
[root@6b564bd3e2b2 scenarios]# ./provision_smartcity.sh
Traceback (most recent call last):
  File "./createNewService.py", line 36, in <module>
    from settings.common import LOGGING
ImportError: No module named settings.common
Error found while Creating service. Code: 1. Aborting

Does anyone know what's going on?
Best regard.

**Comment by amfgomez** [comment]
I have tried to install the simple-setting module, this module contains the library LOGGING, but it always return the same response.

**Comment by AlvaroVega** [comment]
Please, make sure that  $PYTHONPATH is pointing to orchestrator/src folder
