### ISSUE TITLE
Orchestrator problem executing the python script inside the container

### ISSUE THREAD

**Issue by amfgomez** [telefonicaid/orchestrator#167]
Hello 

I have a container with orchestrator in version 2.1.1 and when I want to execute a python script happen below.
cd orchestrator/commands
python ./createNewService.py http keystone 5001 admin_domain cloud_admin password test "servicio de test" admin_test password http localhost  7070

The python script returns me this error:

Traceback (most recent call last):
  File "./createNewService.py", line 36, in <module>
    from settings.common import LOGGING
ImportError: No module named settings.common

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/orchestrator/pull/168

@amfgomez could you confirm and close the issue in positive case, pls? Thx!

**Comment by amfgomez** [comment]
At the moment, I can not evaluate the solution. In 2 weeks, more and less, I check the new DockerFile.
Thank you very much.
Best regard.

**Comment by fgalan** [comment]
Let's do it the other way arround.

I mean, by the moment we are going to close the issue, assuming it is fixed. If after your test in 2 weeks you find it is not fixed, then we can reopen it.
