### ISSUE TITLE
Add STH index to optimize queries on its collections

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/orchestrator#192]
https://github.com/telefonicaid/orchestrator/blob/master/src/orchestrator/core/mongo.py#L52

**Comment by AlvaroVega** [comment]
STH agregated data:
```
data_expiration	no	0	Collections will be removed if older than the value specified in seconds. The reference of time is the one stored in the _id.origin property. Set to 0 if not wanting this policy.
```

STH raw data:
```
collections_size	no	0	The oldest data (according to insertion time) will be removed if the size of the data collection gets bigger than the value specified in bytes. Notice that the size-based truncation policy takes precedence over the time-based one. Set to 0 if not wanting this policy. Minimum value (different than 0) is 4096 bytes.
```

**Comment by fgalan** [comment]
I understand data_expiration and collections_size are Cygnus parameters.

Does it mean that the scope of the issue has changed? I mean, from "Add STH index based on time" to "Addd Cygnus configuration to enable STH capping" (or something like that).

**Comment by AlvaroVega** [comment]
STH collection name has by default the following format:
sth_<service_or_subservice>_<entity_id>_<entity_type>
sth_<service_or_subservice>_<entity_id>_<entity_type>.aggr

So there is no way to know entity_id and entity_type at service or subservice creation time

**Comment by AlvaroVega** [comment]
```
db['sth_/subservicio.aggr'].createIndex({ "_id.entityId": 1, "_id.entityType": 1, "_id.attrName": 1, "_id.resolution": 1, "_id.origin": 1 })
```

**Comment by fgalan** [comment]
An index for the raw collection should be also created (the one described at https://github.com/telefonicaid/fiware-sth-comet/blob/master/doc/manuals/db_indexes.md#indexes-in-the-raw-data-collection). The analogous command for that would be:

```
db['sth_/subservicio'].createIndex({entityId: 1, entityType: 1, attrName: 1, recvTime: -1})
```

**Comment by fgalan** [comment]
(Actually more than "Add STH index based on time" these two new indexes will fit with "Add STH index to optimize queries on its collections")

**Comment by AlvaroVega** [comment]
In my mongo I'm see:
collection 
![mongo_sth_collections](https://user-images.githubusercontent.com/983422/57598735-a6f09c80-7554-11e9-8279-8e5f2a0266cb.png)

that's it:
```
database_name = sth_<service>
collection_name = sth_<service>/_
collection_name = sth_<service>/<subservice>_
```

with a final `_`. @fgalan it's correct?

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/orchestrator/pull/204
