### ISSUE TITLE
createIndex database exception: not enough arguments for format string

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/orchestrator#214]
time=2019-06-27T08:13:06.274Z | lvl=WARNING | corr=ec33af3f-c0f7-46d0-9994-4229ac845025 | trans=ec33af3f-c0f7-46d0-9994-4229ac845025 | srv=None | subsrv=/ | comp=Orchestrator | op=orchestrator_core:createOrionIndexes() | msg=createIndex database orion-s026pep2cbv2 exception: not enough arguments for format string
time=2019-06-27T08:13:06.278Z | lvl=WARNING | corr=ec33af3f-c0f7-46d0-9994-4229ac845025 | trans=ec33af3f-c0f7-46d0-9994-4229ac845025 | srv=None | subsrv=/ | comp=Orchestrator | op=orchestrator_core:createSTHIndexes() | msg=createIndex database sth_s026pep2cbv2 exception: not enough arguments for format string

**Comment by fgalan** [comment]
Implemented by PR https://github.com/telefonicaid/orchestrator/pull/215/
