### ISSUE TITLE
Adjust orchestrator spec file for RPM

### ISSUE THREAD

**Issue by cesarjorgemartinez** [telefonicaid/orchestrator#238]
We need to adjust correctly the orchestrator spec file for RPM generate and use.

Includes:
- remove old comments
- fix indent
- no dereference links
- assure remove link
- remove repeated directories
- not be verbose
- indent and write correctly
- remove bad create links
- move files section to the end file
- manage correctly user add orchestrator 

We need to include at master and at least the release/2.10.0 (last in Platform) and release/3.0.0.

**Comment by cesarjorgemartinez** [comment]
Done in PR https://github.com/telefonicaid/orchestrator/issues/238

**Comment by fgalan** [comment]
Should this issue be closed given that PR #239 has been already merged? Or is there anything pending from the original list?
