### ISSUE TITLE
upgrade to Python 3 

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/orchestrator#242]
Python2.7 is not supported any more: 
Python 2.7.18 will be last release of python 2.7

https://www.python.org/dev/peps/pep-0373/#maintenance-releases

Some places where python2.7 is wired:
https://github.com/telefonicaid/orchestrator/blob/master/Dockerfile#L56
https://github.com/telefonicaid/orchestrator/blob/master/orchestrator.spec#L23
https://github.com/telefonicaid/orchestrator/blob/master/orchestrator.spec#L24

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/orchestrator/pull/313
