### ISSUE TITLE
check if admin to not do unsucessful operations 

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/orchestrator#246]
Performance improvement.
Check if user is cloud_admin to avoid try perform operations that are not allowed (like delete subscriptions or rules)

**Comment by AlvaroVega** [comment]
implemented in https://github.com/telefonicaid/orchestrator/pull/252

**Comment by fgalan** [comment]
Implemented by PR https://github.com/telefonicaid/orchestrator/pull/252
