### ISSUE TITLE
[DOC] Review documentation for orchestrator

### ISSUE THREAD

**Issue by cesarjorgemartinez** [telefonicaid/orchestrator#30]
Things detected:
- Alarms section missing (go to a troubleshooting section)
- Alarms definition
- Missing new parameters
- General review text and links

**Comment by AlvaroVega** [comment]
Currently troubleshooting section is about logs and errors

**Comment by AlvaroVega** [comment]
Some works were done in PR https://github.com/telefonicaid/orchestrator/pull/41
