### ISSUE TITLE
Orion geo-index should be created upon creation of new service

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/orchestrator#301]
ORCH creates entities collection on service provision with a set of predefined indexes for performance. However, it doesn't create an index for geolocation which can cause ERROR traces if subscriptions with geo-filter expression are created without skipping initial notification before the first entity is created (see https://github.com/telefonicaid/fiware-orion/issues/3729)

**Comment by AlvaroVega** [comment]
https://github.com/telefonicaid/orchestrator/blob/aab628d1dce8969043fdcd01ace2f46500ffe832/src/orchestrator/core/mongo.py#L48-L60

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/orchestrator/pull/302
