### ISSUE TITLE
Upgrade djangorestframework

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/orchestrator#310]
needs: https://github.com/telefonicaid/orchestrator/issues/242 and https://github.com/telefonicaid/orchestrator/issues/309

https://github.com/telefonicaid/orchestrator/security/dependabot/requirements.txt/djangorestframework/open

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/orchestrator/pull/313
