### ISSUE TITLE
rename subservice

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/orchestrator#330]
Including:
- [x] Keystone: Using API of keystone
- [x] Keypass: Keypass already is using projectId (no project name)  to create subject policy. 
- [x] Orion, IotAgents, STH, CEP: using mongo access and relaying in default mongodb database names
- [ ] PG: No access to PG from orchestrator
- [ ] MySQL:  No access to MySQL from orchestrator

**Comment by fgalan** [comment]
PG table/view names?
PG table records?

**Comment by AlvaroVega** [comment]
how upgrade a "_id" value of mongodb: https://stackoverflow.com/questions/4012855/how-to-update-the-id-of-one-mongodb-document

**Comment by AlvaroVega** [comment]
> PG table/view names? PG table records?

PG and MySQL table names and records are afected by Cygnus datamodels [1]  and namemappings [2]

So Orch is not able t know what DM or namepapping cygnus applies.

[1] https://github.com/telefonicaid/fiware-cygnus/blob/master/doc/cygnus-ngsi/flume_extensions_catalogue/ngsi_postgresql_sink.md#postgresql-tables-naming-conventions
[2] https://github.com/telefonicaid/fiware-cygnus/blob/master/doc/cygnus-ngsi/installation_and_administration_guide/name_mappings.md

**Comment by fgalan** [comment]
> > PG table/view names? PG table records?
> 
> PG and MySQL table names and records are afected by Cygnus datamodels [1] and namemappings [2]
> 
> So Orch is not able t know what DM or namepapping cygnus applies.
> 
> [1] https://github.com/telefonicaid/fiware-cygnus/blob/master/doc/cygnus-ngsi/flume_extensions_catalogue/ngsi_postgresql_sink.md#postgresql-tables-naming-conventions [2] https://github.com/telefonicaid/fiware-cygnus/blob/master/doc/cygnus-ngsi/installation_and_administration_guide/name_mappings.md

That means that renaming PG table/view names and PG table record would require some ad hoc manual procedure, isn't it?

**Comment by fgalan** [comment]
> > That means that renaming PG table/view names and PG table record would require some ad hoc manual procedure, isn't it?
> 
> Yeah

Maybe it would be a good idea to include this caveat it the documentation of the new operation.

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/orchestrator/pull/331
