### ISSUE TITLE
Detected performance issues in component https://github.com/telefonicaid/fiware-orion because missing indexes in orion dbs collection entities

### ISSUE THREAD

**Issue by cesarjorgemartinez** [telefonicaid/orchestrator#335]
Detected performance issues in component https://github.com/telefonicaid/fiware-orion because missing indexes in orion dbs collection entities

I detected performance issues in Orion operations because missing the following indexes in orion databases inside the collection entities:

```
db[entities].createIndex({_id.id : 1})
db[entities].createIndex({_id.type : 1})
db[entities].createIndex({_id.servicePath : 1})
db[entities].createIndex({attrNames : 1})
```

I need to generate a new version of orchestrator to deploy.

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/orchestrator/pull/336 adding the new indexes (and side PR in Orion repository to add them to documentation PR https://github.com/telefonicaid/fiware-orion/pull/4170)
