### ISSUE TITLE
uwsgi listen queue  full 

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/orchestrator#352]
uwsgi-http] unable to connect() to node "127.0.0.1:36861" (3 retries): Connection timed out
Mon Apr  1 08:07:19 2024 - ** uWSGI listen queue of socket "127.0.0.1:36861" (fd: 3) full !!! (101/100) **
Mon Apr  1 08:07:20 2024 - ** uWSGI listen queue of socket "127.0.0.1:36861" (fd: 3) full !!! (101/100) **

**Comment by AlvaroVega** [comment]
maybe related with  uwsgi_listen_queue_size. Try to increase 1024

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/orchestrator/pull/353
