### ISSUE TITLE
Missing documentation on login details for the docker set-up

### ISSUE THREAD

**Issue by chicco785** [telefonicaid/orchestrator#70]
Hi,
I wanted to play with the tool and launched the docker compose. But I can't find a proper login.
The only one working is:
- user: nagios
- pwd: 4pass1w0rd
- domain: Default

once logged in i get several errors:
Internal server error. Please try again later
reference: Fiware-Correlator 471511f6-1322-4209-862e-6233da508baf

So i suppose it's not this the correct login.

Also, is there any way to access the code repository for the ui.

Cheers,
Federico

**Comment by AlvaroVega** [comment]
Hi Chicco,
Orchestrator do not keeps any credentials. Orchestrator needs a Identity Manager to work. You should search that credentials into your IdentityManager.

Regards,
Álvaro

**Comment by chicco785** [comment]
Thanks Alvaro, the comment was referred to the fact that you provide a docker recipe that reading the docs is supposed to be "Ready to Use".

Also, as mentioned, I could not find anywhere the code base for the GUI, while it is available as Docker image. Is that closed source?

Cheers,
Federico

**Comment by AlvaroVega** [comment]
Orchestrator is ready to use with and Idm :)
GUI is not open source. 
BTW, Orchestrator and GUI are not fiware components.
