### ISSUE TITLE
expose more conf into docker

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/orchestrator#98]
- IoTModules (default are CYGNUS, PERSEO)
- LogLevel (default is INFO)

**Comment by AlvaroVega** [comment]
related https://github.com/telefonicaid/orchestrator/pull/176 https://github.com/telefonicaid/orchestrator/pull/170

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/orchestrator/pull/179
